services:
  portfolio:
    image: mauritsschelvis87-crypto/portfolio-page:latest
    container_name: portfolio
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: reverse-proxy_proxy
